-- 1. Insert an active treating physician
INSERT INTO "DOCTOR" ("D_ID", "DOCTOR_FIRSTNAME", "DOCTOR_LASTNAME", "DOCTOR_SPECIALIZATION", "DOCTOR_AVAILABILITY", "DOCTOR_PHNO") 
VALUES (1, 'Swaroop', 'Kumar', 'Cardiology', 'AVAILABLE', '9876543210');

-- 2. Insert a primary patient file record
INSERT INTO "PATIENT" ("PID", "PATIENT_FIRSTNAME", "PATIENT_LASTNAME", "PATIENT_DOB", "PATIENT_GENDER", "PATIENT_BLOODGROUP", "PATIENT_ADDRESS", "PATIENT_PHNO") 
VALUES (1, 'Sai', 'Karthik', '2000-01-01', 'MALE', 'O+', 'Nellore District', '9998887776');

-- 3. Schedule a linked appointment entry for today
INSERT INTO "APPOINTMENT" ("AID", "PATIENT_ID", "DOCTOR_ID", "APPOINTMENT_DATE", "APPOINTMENT_TIME", "APPOINTMENT_VISIT_TYPE", "APPOINTMENT_STATUS") 
VALUES (1, 1, 1, '2026-06-06', '10:30 AM', 'NEW', 'SCHEDULED');